"""Initial migration - nodes, tasks, users tables

Revision ID: 72484241599b
Revises: 
Create Date: 2026-04-22 23:32:35.926460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72484241599b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'node_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('tasks', 'node_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('nodes', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
