#!/usr/bin/env python3
"""Send .docx contract via email using existing send_email infrastructure."""
import sys
import os
sys.path.insert(0, '/root/.openclaw/workspace')

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders

# 邮件账户配置（复用 STD-003）
MAIL_ACCOUNTS = [
    {
        "name": "QQ邮箱",
        "addr": "19525456@qq.com",
        "smtp": "smtp.qq.com",
        "port": 465,
        "password": "bzgwylbbrocdbiie",
    },
    {
        "name": "163邮箱",
        "addr": "chenqifu_fzu@163.com",
        "smtp": "smtp.163.com",
        "port": 465,
        "password": "AWZBPidhza74EbV8",  # 备用（原主授权码 ormxhluuafwnbgei 已退役）
    },
]

def send_docx_attachment(to_addr, subject, docx_path, account_index=0):
    acct = MAIL_ACCOUNTS[account_index]
    
    msg = MIMEMultipart('mixed')
    msg['From'] = acct["addr"]
    msg['To'] = to_addr
    msg['Subject'] = subject

    # HTML body
    html = '''<html><body style="font-family:SimSun, serif; padding:20px;">
<h2>数载生态伙伴平台服务合同</h2>
<p>老大，这是根据您的意见修改后的合同版本：</p>
<ul>
  <li>合同性质从"购买服务"改为<strong>"平台生态合作"</strong></li>
  <li>新增<strong>数据归属条款</strong>（数据归甲方）</li>
  <li>新增<strong>金融服务通道条款</strong></li>
  <li>删除乙方<strong>单方变更权</strong></li>
  <li>增加<strong>SLA标准</strong>和<strong>赔偿上限</strong></li>
  <li>争议管辖改为<strong>甲方所在地法院</strong></li>
</ul>
<p style="color:#666;">附件为 .docx 格式合同文件，可直接用 Word 打开和编辑。</p>
<hr>
<p style="color:#999;">Generated by 小智 · 2026-05-21 05:38</p>
</body></html>'''
    msg.attach(MIMEText(html, 'html', 'utf-8'))

    # Attach the docx
    with open(docx_path, 'rb') as f:
        file_data = f.read()
    
    part = MIMEBase('application', 'vnd.openxmlformats-officedocument.wordprocessingml.document')
    part.set_payload(file_data)
    encoders.encode_base64(part)
    fname = os.path.basename(docx_path)
    # Use URL-encoded filename for compatibility
    part.add_header('Content-Disposition', f'attachment; filename="{fname}"')
    part.add_header('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    msg.attach(part)

    try:
        smtp = smtplib.SMTP_SSL(acct["smtp"], acct["port"], timeout=15)
        smtp.login(acct["addr"], acct["password"])
        smtp.sendmail(acct["addr"], [to_addr], msg.as_string())
        smtp.quit()
        print(f"✅ 已通过 {acct['name']} 发送到 {to_addr}")
        return True
    except smtplib.SMTPServerDisconnected:
        print(f"❌ {acct['name']} 连接断开")
        return False
    except smtplib.SMTPAuthenticationError as e:
        print(f"❌ {acct['name']} 认证失败: {e}")
        return False
    except Exception as e:
        print(f"❌ {acct['name']} 发送失败: {e}")
        return False


def main():
    to_addr = "19525456@qq.com"
    subject = "数载生态伙伴平台服务合同（中物版）修改版"
    docx_path = "/root/.openclaw/workspace/ai_agent/results/数载生态伙伴平台服务合同_中物版.docx"

    if not os.path.exists(docx_path):
        print(f"❌ 文件不存在: {docx_path}")
        sys.exit(1)
    
    print(f"📧 发送邮件...")
    print(f"   收件人: {to_addr}")
    print(f"   主题:   {subject}")
    print(f"   文件:   {docx_path}")
    print(f"   大小:   {os.path.getsize(docx_path)/1024:.1f} KB")
    print()

    # 尝试 QQ 优先
    print("→ 尝试 QQ 邮箱...")
    if send_docx_attachment(to_addr, subject, docx_path, 0):
        return
    
    # QQ 失败切 163
    print("→ QQ 失败，切换 163 邮箱...")
    if send_docx_attachment(to_addr, subject, docx_path, 1):
        return

    print("❌ 所有邮箱发送失败")
    sys.exit(1)


if __name__ == '__main__':
    main()
