#!/bin/bash
# 快速帮助脚本
echo "🚀 可用命令提示:"
echo "=================="
echo "🔧 系统命令:"
echo "  openclaw    - OpenClaw控制"
echo "  ssh         - SSH客户端"
echo "  curl        - HTTP客户端"
echo "  ping        - 网络测试"
echo "  python      - Python解释器"
echo ""
echo "📁 文件操作:"
echo "  ls, cd, cp, mv, rm, mkdir"
echo "  nano, vim   - 文本编辑器"
echo "  find, grep  - 搜索工具"
echo ""
echo "🌐 网络工具:"
echo "  sshd        - SSH服务"
echo "  netstat     - 网络状态"
echo "  ps          - 进程查看"
echo ""
echo "💡 开发工具:"
echo "  node, npm   - Node.js"
echo "  git         - 版本控制"
echo ""
echo "❌ 不可用命令:"
echo "  traceroute  - 需要root权限"
echo "  iptables    - 需要root权限"
echo ""
echo "📝 提示: 输入 'which 命令名' 检查命令位置"