#!/bin/bash
# 手动安全加固指南
# 由于权限限制，请在目标服务器(192.168.1.7)上手动执行以下步骤

echo "=========================================="
echo "     手动安全加固指南"
echo "     目标: 192.168.1.7"
echo "=========================================="
echo ""
echo "请在目标服务器上执行以下命令："
echo ""
echo "# 1. 切换到root用户"
echo "sudo su -"
echo ""
echo "# 2. 安装UFW（如未安装）"
echo "apt-get update && apt-get install -y ufw"
echo ""
echo "# 3. 配置防火墙规则"
echo "ufw default deny incoming"
echo "ufw default allow outgoing"
echo ""
echo "# 4. 允许必要服务"
echo "ufw allow 22/tcp                      # SSH"
echo "ufw allow from 192.168.1.0/24 to any port 11434   # Ollama API仅限内网"
echo ""
echo "# 5. 阻止高危端口"
echo "ufw deny 135/tcp                      # MSRPC"
echo "ufw deny 139/tcp                      # NetBIOS"
echo "ufw deny 445/tcp                      # SMB"
echo ""
echo "# 6. 启用防火墙"
echo "ufw enable"
echo ""
echo "# 7. 查看状态"
echo "ufw status verbose"
echo ""
echo "=========================================="
echo "     加固完成后的预期状态："
echo "=========================================="
echo "  ✅ 允许: 22 (SSH)"
echo "  ✅ 允许: 11434 (Ollama API, 仅限192.168.1.x)"
echo "  ❌ 阻止: 135 (MSRPC)"
echo "  ❌ 阻止: 139 (NetBIOS)"
echo "  ❌ 阻止: 445 (SMB)"
echo ""
echo "如需撤销规则："
echo "  ufw delete deny 135/tcp"
echo "  ufw disable          # 临时禁用防火墙"
echo "  ufw reset            # 重置所有规则"
echo ""